/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetAdminSessionsParams
} from '../../model';





/**
 * @summary Get dashboard statistics
 */
export const getAdminStats = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/admin/stats`,options
    );
  }




export const getGetAdminStatsQueryKey = () => {
    return [
    `/api/admin/stats`
    ] as const;
    }

    
export const getGetAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStats>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({ signal }) => getAdminStats({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStats>>>
export type GetAdminStatsQueryError = AxiosError<unknown>


export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminStats>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminStats>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard statistics
 */

export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get paginated list of sessions
 */
export const getAdminSessions = (
    params?: GetAdminSessionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/admin/sessions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAdminSessionsQueryKey = (params?: GetAdminSessionsParams,) => {
    return [
    `/api/admin/sessions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSessions>>, TError = AxiosError<unknown>>(params?: GetAdminSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSessionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSessions>>> = ({ signal }) => getAdminSessions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSessions>>>
export type GetAdminSessionsQueryError = AxiosError<unknown>


export function useGetAdminSessions<TData = Awaited<ReturnType<typeof getAdminSessions>>, TError = AxiosError<unknown>>(
 params: undefined |  GetAdminSessionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSessions>>,
          TError,
          Awaited<ReturnType<typeof getAdminSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSessions<TData = Awaited<ReturnType<typeof getAdminSessions>>, TError = AxiosError<unknown>>(
 params?: GetAdminSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSessions>>,
          TError,
          Awaited<ReturnType<typeof getAdminSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSessions<TData = Awaited<ReturnType<typeof getAdminSessions>>, TError = AxiosError<unknown>>(
 params?: GetAdminSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated list of sessions
 */

export function useGetAdminSessions<TData = Awaited<ReturnType<typeof getAdminSessions>>, TError = AxiosError<unknown>>(
 params?: GetAdminSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Resend email to customer
 */
export const resendSessionEmail = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/admin/sessions/${id}/resend-email`,undefined,options
    );
  }



export const getResendSessionEmailMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendSessionEmail>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof resendSessionEmail>>, TError,{id: string}, TContext> => {

const mutationKey = ['resendSessionEmail'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resendSessionEmail>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  resendSessionEmail(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResendSessionEmailMutationResult = NonNullable<Awaited<ReturnType<typeof resendSessionEmail>>>
    
    export type ResendSessionEmailMutationError = AxiosError<unknown>

    /**
 * @summary Resend email to customer
 */
export const useResendSessionEmail = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendSessionEmail>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resendSessionEmail>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getResendSessionEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    