/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */

/**
 * Optional initial configuration object
 */
export type CreateSessionDtoConfig = { [key: string]: unknown };
