/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */

export type GetAdminSessionsParams = {
/**
 * Page number (default: 1)
 */
page?: number;
/**
 * Items per page (default: 10)
 */
limit?: number;
};
