/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import type { MediaType } from './mediaType';

export interface Media {
  /** The unique identifier of the media */
  id: string;
  /** The absolute URL path of the media file */
  url: string;
  /** The type of the media file */
  type: MediaType;
}
