/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import type { SessionStatus } from './sessionStatus';
import type { Media } from './media';

export interface Session {
  /** The unique identifier of the session */
  id: string;
  /** The current status of the session */
  status: SessionStatus;
  /**
   * Selected filter identifier
   * @nullable
   */
  selectedFilter: string | null;
  /**
   * Selected frame identifier
   * @nullable
   */
  selectedFrame: string | null;
  /** Whether the session output is mirrored */
  isMirrored: boolean;
  /** The date and time when the session was created */
  createdAt: string;
  /** List of media files associated with the session */
  medias: Media[];
}
