/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import type { UpdateSessionDtoStatus } from './updateSessionDtoStatus';

export interface UpdateSessionDto {
  status?: UpdateSessionDtoStatus;
  /** Selected filter identifier */
  selectedFilter?: string;
  /** Selected frame identifier */
  selectedFrame?: string;
}
