/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */

export type UpdateSessionDtoStatus = typeof UpdateSessionDtoStatus[keyof typeof UpdateSessionDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSessionDtoStatus = {
  INIT: 'INIT',
  SELECTING: 'SELECTING',
  COUNTDOWN: 'COUNTDOWN',
  CAPTURING: 'CAPTURING',
  COMPLETED: 'COMPLETED',
} as const;
