/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */

export type UploadSessionMediaType = typeof UploadSessionMediaType[keyof typeof UploadSessionMediaType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadSessionMediaType = {
  ORIGINAL: 'ORIGINAL',
  PROCESSED: 'PROCESSED',
  VIDEO: 'VIDEO',
  SIGNATURE: 'SIGNATURE',
} as const;

