/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import type { UploadSessionMediaType } from './uploadSessionMediaType';

export type UploadSessionMediaParams = {
/**
 * Type of media (default: ORIGINAL)
 */
type?: UploadSessionMediaType;
};
