/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Photobooth API
 * The Photobooth Backend API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSessionDto,
  Media,
  Session,
  UpdateSessionDto,
  UploadSessionMediaBody,
  UploadSessionMediaParams
} from '../../model';





/**
 * @summary Create a new session
 */
export const createSession = (
    createSessionDto: CreateSessionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Session>> => {
    
    
    return axios.post(
      `/api/sessions`,
      createSessionDto,options
    );
  }



export const getCreateSessionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionDto}, TContext> => {

const mutationKey = ['createSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSession>>, {data: CreateSessionDto}> = (props) => {
          const {data} = props ?? {};

          return  createSession(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>
    export type CreateSessionMutationBody = CreateSessionDto
    export type CreateSessionMutationError = AxiosError<unknown>

    /**
 * @summary Create a new session
 */
export const useCreateSession = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSession>>,
        TError,
        {data: CreateSessionDto},
        TContext
      > => {

      const mutationOptions = getCreateSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List all sessions
 */
export const getSessions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Session[]>> => {
    
    
    return axios.get(
      `/api/sessions`,options
    );
  }




export const getGetSessionsQueryKey = () => {
    return [
    `/api/sessions`
    ] as const;
    }

    
export const getGetSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getSessions>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessions>>> = ({ signal }) => getSessions({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSessions>>>
export type GetSessionsQueryError = AxiosError<unknown>


export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessions>>,
          TError,
          Awaited<ReturnType<typeof getSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessions>>,
          TError,
          Awaited<ReturnType<typeof getSessions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all sessions
 */

export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update an existing session
 */
export const updateSession = (
    id: string,
    updateSessionDto: UpdateSessionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Session>> => {
    
    
    return axios.patch(
      `/api/sessions/${id}`,
      updateSessionDto,options
    );
  }



export const getUpdateSessionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionDto}, TContext> => {

const mutationKey = ['updateSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSession>>, {id: string;data: UpdateSessionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSession(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSession>>>
    export type UpdateSessionMutationBody = UpdateSessionDto
    export type UpdateSessionMutationError = AxiosError<unknown>

    /**
 * @summary Update an existing session
 */
export const useUpdateSession = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSession>>,
        TError,
        {id: string;data: UpdateSessionDto},
        TContext
      > => {

      const mutationOptions = getUpdateSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get session details by ID
 */
export const getSession = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Session>> => {
    
    
    return axios.get(
      `/api/sessions/${id}`,options
    );
  }




export const getGetSessionQueryKey = (id?: string,) => {
    return [
    `/api/sessions/${id}`
    ] as const;
    }

    
export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = AxiosError<unknown>


export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get session details by ID
 */

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Mark a session as completed
 */
export const completeSession = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Session>> => {
    
    
    return axios.post(
      `/api/sessions/${id}/complete`,undefined,options
    );
  }



export const getCompleteSessionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSession>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof completeSession>>, TError,{id: string}, TContext> => {

const mutationKey = ['completeSession'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeSession>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  completeSession(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof completeSession>>>
    
    export type CompleteSessionMutationError = AxiosError<unknown>

    /**
 * @summary Mark a session as completed
 */
export const useCompleteSession = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSession>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeSession>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCompleteSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Upload a media file (WebM automatically converted to MP4)
 */
export const uploadSessionMedia = (
    id: string,
    uploadSessionMediaBody: UploadSessionMediaBody,
    params?: UploadSessionMediaParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Media>> => {
    
    const formData = new FormData();
if(uploadSessionMediaBody.file !== undefined) {
 formData.append(`file`, uploadSessionMediaBody.file)
 }

    return axios.post(
      `/api/sessions/${id}/upload`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getUploadSessionMediaMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSessionMedia>>, TError,{id: string;data: UploadSessionMediaBody;params?: UploadSessionMediaParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof uploadSessionMedia>>, TError,{id: string;data: UploadSessionMediaBody;params?: UploadSessionMediaParams}, TContext> => {

const mutationKey = ['uploadSessionMedia'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadSessionMedia>>, {id: string;data: UploadSessionMediaBody;params?: UploadSessionMediaParams}> = (props) => {
          const {id,data,params} = props ?? {};

          return  uploadSessionMedia(id,data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadSessionMediaMutationResult = NonNullable<Awaited<ReturnType<typeof uploadSessionMedia>>>
    export type UploadSessionMediaMutationBody = UploadSessionMediaBody
    export type UploadSessionMediaMutationError = AxiosError<unknown>

    /**
 * @summary Upload a media file (WebM automatically converted to MP4)
 */
export const useUploadSessionMedia = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSessionMedia>>, TError,{id: string;data: UploadSessionMediaBody;params?: UploadSessionMediaParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadSessionMedia>>,
        TError,
        {id: string;data: UploadSessionMediaBody;params?: UploadSessionMediaParams},
        TContext
      > => {

      const mutationOptions = getUploadSessionMediaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    